# Generated by Django 2.1.7 on 2019-03-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190321_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer_name',
            new_name='organizer_id',
        ),
    ]
