# Generated by Django 2.1.7 on 2019-03-24 22:37

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190322_1843'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('search_results', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
